apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
  labels:
    app: authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
    spec:
      volumes:
        - name: vol-config
          configMap:
            name: config
        - name: vol-cert
          secret:
             secretName: cert
      containers:
        - name: authz
          image: wukongsun/authz-amd64:v0.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vol-config
              mountPath: /etc/apiserver
            - name: vol-cert
              mountPath: /etc/apiserver/cert
          ports:
            - containerPort: 8080
              name: insecure
              protocol: TCP
            - containerPort: 8081
              name: rpc
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: authz
spec:
  selector:
    app: authz
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30090
  - name: rpc
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 30091


